backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "/source/assets/images"
# public_folder: "/assets/images"
public_folder: "/source"

collections:
- name: "name from collection" # Used in routes, e.g., /admin/collections/blog
  label: "label from collection" # Used in the UI
  folder: "_posts"
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Body", name: "body", widget: "markdown"}